method: bayes
name: SAM_CLIP_TTA_Parameters_Only_Memory  # project的名字，在网站中可以看到
program: TTA/main_wandb.py
metric:
  name: dice
  goal: maximize


# 搜索边界
parameters:
  alpha:  # ema alpha
    values: [0.1, 0.3, 0.5, 0.7, 0.9, 0.99, 0.999]
  threshold:  # refine crf_map threshold
    values: [50, 80]  # cxr_lung的不能太高
  memory_size:
    values: [40, 60, 80]
  neighbor_size:
    values: [12, 16, 32]
  learning_rate:  # 这里要补充，因为main哪里我是用这个赋值的，所以得加一下
    values: [0]
  lora_block: # 更新多少个block
    values: [0]
