method: bayes
name: SAM_CLIP_TTA_Parameters  # project的名字
program: TTA/main_wandb.py
metric:
  name: dice
  goal: maximize


# 搜索边界
parameters:
  learning_rate:
    values: [1e-5, 1e-6]  # [1e-5, 1e-7, 8e-6, 1e-6]
  alpha:  # ema alpha
    values: [0.9]  # [0.5, 0.7, 0.9, 0.99, 0.999]
  threshold:  # refine crf_map threshold
    values: [50]  # cxr_lung的不能太高
  memory_size:
    values: [40, 80]
  neighbor_size:
    values: [16, 32]
  lora_block:  # 更新多少个block
    values: [1, 3, 5]
